import plugin from "tailwindcss/plugin";

const darkTheme = {
  "--radius": "0.625rem",
  "--background": "oklch(0.145 0 0)",
  "--foreground": "oklch(0.985 0 0)",
  "--surface-canvas": "oklch(0.08 0 0)",
  "--surface-hero": "oklch(0.18 0 0)",
  "--surface-panel": "oklch(0.22 0 0 / 80%)",
  "--surface-panel-muted": "oklch(1 0 0 / 10%)",
  "--surface-section": "oklch(0.16 0 0)",
  "--brand-primary": "oklch(0.82 0.14 82)",
  "--brand-primary-foreground": "oklch(0.08 0 0)",
  "--card": "oklch(0.205 0 0)",
  "--card-foreground": "oklch(0.985 0 0)",
  "--popover": "oklch(0.205 0 0)",
  "--popover-foreground": "oklch(0.985 0 0)",
  "--primary": "oklch(0.922 0 0)",
  "--primary-foreground": "oklch(0.205 0 0)",
  "--secondary": "oklch(0.269 0 0)",
  "--secondary-foreground": "oklch(0.985 0 0)",
  "--muted": "oklch(0.269 0 0)",
  "--muted-foreground": "oklch(0.708 0 0)",
  "--accent": "oklch(0.269 0 0)",
  "--accent-foreground": "oklch(0.985 0 0)",
  "--destructive": "oklch(0.577 0.245 27.325)",
  "--border": "oklch(1 0 0 / 10%)",
  "--input": "oklch(1 0 0 / 15%)",
  "--ring": "oklch(0.82 0.14 205)",
  "--game-blue-card": "oklch(0.34 0.07 246)",
  "--game-blue-showcase": "oklch(0.22 0.08 250)",
  "--game-blue-gradient": "oklch(0.28 0.12 258)",
  "--game-purple-card": "oklch(0.28 0.08 295)",
  "--game-purple-showcase": "oklch(0.22 0.09 305)",
  "--game-purple-gradient": "oklch(0.29 0.13 303)",
  "--game-green-card": "oklch(0.31 0.07 155)",
  "--game-green-showcase": "oklch(0.21 0.08 150)",
  "--game-green-gradient": "oklch(0.28 0.11 153)",
  "--game-pink-card": "oklch(0.33 0.09 355)",
  "--game-pink-showcase": "oklch(0.24 0.1 360)",
  "--game-pink-gradient": "oklch(0.31 0.13 358)",
  "--chart-1": "oklch(0.646 0.222 41.116)",
  "--chart-2": "oklch(0.6 0.118 184.704)",
  "--chart-3": "oklch(0.398 0.07 227.392)",
  "--chart-4": "oklch(0.828 0.189 84.429)",
  "--chart-5": "oklch(0.769 0.188 70.08)",
  "--sidebar": "oklch(0.205 0 0)",
  "--sidebar-foreground": "oklch(0.985 0 0)",
  "--sidebar-primary": "oklch(0.488 0.243 264.376)",
  "--sidebar-primary-foreground": "oklch(0.985 0 0)",
  "--sidebar-accent": "oklch(0.269 0 0)",
  "--sidebar-accent-foreground": "oklch(0.985 0 0)",
  "--sidebar-border": "oklch(1 0 0 / 10%)",
  "--sidebar-ring": "oklch(0.556 0 0)",
  "--shadow-card-lifted": "0 20px 40px rgb(0 0 0 / 60%)",
};

const lightTheme = {
  ...darkTheme,
  "--background": "oklch(0.96 0 0)",
  "--foreground": "oklch(0.16 0 0)",
  "--surface-canvas": "oklch(0.94 0 0)",
  "--surface-hero": "oklch(0.84 0 0)",
  "--surface-panel": "oklch(0.98 0 0 / 92%)",
  "--surface-panel-muted": "oklch(0.18 0 0 / 8%)",
  "--surface-section": "oklch(0.9 0 0)",
  "--brand-primary": "oklch(0.76 0.15 82)",
  "--brand-primary-foreground": "oklch(0.12 0 0)",
  "--card": "oklch(0.98 0 0)",
  "--card-foreground": "oklch(0.16 0 0)",
  "--popover": "oklch(0.98 0 0)",
  "--popover-foreground": "oklch(0.16 0 0)",
  "--primary": "oklch(0.18 0 0)",
  "--primary-foreground": "oklch(0.98 0 0)",
  "--secondary": "oklch(0.9 0 0)",
  "--secondary-foreground": "oklch(0.2 0 0)",
  "--muted": "oklch(0.88 0 0)",
  "--muted-foreground": "oklch(0.38 0 0)",
  "--accent": "oklch(0.9 0 0)",
  "--accent-foreground": "oklch(0.2 0 0)",
  "--border": "oklch(0.2 0 0 / 14%)",
  "--input": "oklch(0.2 0 0 / 14%)",
  "--ring": "oklch(0.42 0.08 205)",
  "--shadow-card-lifted": "0 20px 40px rgb(0 0 0 / 16%)",
};

const config = {
  darkMode: ["class", ".dark"],
  content: ["./src/**/*.{html,ts,tsx}", "./styles/**/*.css"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "surface-canvas": "var(--surface-canvas)",
        "surface-hero": "var(--surface-hero)",
        "surface-panel": "var(--surface-panel)",
        "surface-panel-muted": "var(--surface-panel-muted)",
        "surface-section": "var(--surface-section)",
        "brand-primary": "var(--brand-primary)",
        "brand-primary-foreground": "var(--brand-primary-foreground)",
        "game-blue-card": "var(--game-blue-card)",
        "game-blue-showcase": "var(--game-blue-showcase)",
        "game-blue-gradient": "var(--game-blue-gradient)",
        "game-purple-card": "var(--game-purple-card)",
        "game-purple-showcase": "var(--game-purple-showcase)",
        "game-purple-gradient": "var(--game-purple-gradient)",
        "game-green-card": "var(--game-green-card)",
        "game-green-showcase": "var(--game-green-showcase)",
        "game-green-gradient": "var(--game-green-gradient)",
        "game-pink-card": "var(--game-pink-card)",
        "game-pink-showcase": "var(--game-pink-showcase)",
        "game-pink-gradient": "var(--game-pink-gradient)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      boxShadow: {
        "brand-glow": "0 0 20px color-mix(in oklch, var(--brand-primary), transparent 70%)",
        "panel-glow": "0 0 30px color-mix(in oklch, var(--ring), transparent 60%)",
        "card-lifted": "var(--shadow-card-lifted)",
      },
      letterSpacing: {
        "brand-wide": "0.4em",
        label: "0.2em",
      },
    },
  },
  plugins: [
    plugin(({ addBase, addUtilities }) => {
      addBase({
        ":root": darkTheme,
        ".dark": darkTheme,
        ".light": lightTheme,
        "*": {
          borderColor: "var(--border)",
          outlineColor: "color-mix(in oklch, var(--ring), transparent 50%)",
        },
        body: {
          backgroundColor: "var(--background)",
          color: "var(--foreground)",
        },
      });

      addUtilities({
        ".text-shadow-sm": {
          textShadow: "0 1px 2px rgb(0 0 0 / 50%)",
        },
        ".hero-outline-text": {
          "-webkit-text-stroke": "1px rgb(255 255 255 / 20%)",
        },
        ".termplay-raster-field": {
          backgroundImage:
            "linear-gradient(90deg, rgb(255 255 255 / 5%) 1px, transparent 1px), repeating-linear-gradient(0deg, rgb(255 255 255 / 12%) 0 1px, transparent 1px 5px), radial-gradient(circle at 72% 40%, rgb(255 255 255 / 14%), transparent 24rem)",
          backgroundSize: "7rem 100%, 100% 5px, 100% 100%",
          mixBlendMode: "screen",
        },
        ".termplay-character-silhouette": {
          position: "absolute",
          inset: "8% 10% 0 auto",
          width: "min(28rem, 42vw)",
          height: "82%",
          borderRadius: "45% 45% 24% 24%",
          background:
            "radial-gradient(circle at 46% 13%, rgb(66 211 198 / 55%) 0 7%, transparent 8%), radial-gradient(ellipse at 50% 20%, rgb(16 185 178 / 45%) 0 14%, transparent 15%), linear-gradient(90deg, transparent 0 28%, rgb(20 24 31 / 80%) 29% 37%, transparent 38% 62%, rgb(20 24 31 / 80%) 63% 71%, transparent 72%), radial-gradient(ellipse at 50% 43%, rgb(255 255 255 / 42%) 0 18%, rgb(18 21 28 / 88%) 19% 31%, transparent 32%)",
          filter: "contrast(1.25) saturate(0.85)",
          opacity: "0.72",
          pointerEvents: "none",
        },
        ".termplay-character-silhouette::before, .termplay-character-silhouette::after": {
          content: '""',
          position: "absolute",
          top: "18%",
          width: "14%",
          height: "68%",
          borderRadius: "999px",
          background: "linear-gradient(rgb(30 164 158 / 70%), rgb(10 14 20 / 90%))",
        },
        ".termplay-character-silhouette::before": {
          left: "18%",
          transform: "rotate(8deg)",
        },
        ".termplay-character-silhouette::after": {
          right: "18%",
          transform: "rotate(-8deg)",
        },
        ".termplay-effects-off .termplay-raster-field, .termplay-effects-off .termplay-character-silhouette": {
          opacity: "0.08",
        },
        ".light .text-white": {
          color: "var(--foreground)",
        },
        ".light .bg-white": {
          backgroundColor: "var(--foreground)",
        },
      });
    }),
  ],
};

export default config;
